server:
  port: 90

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sweater_db
    username: postgres
    password: Zaebis123++
  jpa:
    generate-ddl: true
  mustache:
    servlet:
      expose-request-attributes: true
